//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NeolithLib.API.Events
{
	public class OwnershipExclusionEvent
	{
		public Controllable User { get; set; }
		public DeployableObject Target { get; set; }
		public bool IsExcluded { get; private set; }

		public OwnershipExclusionEvent (Controllable user, DeployableObject target)
		{
			this.User = user;
			this.Target = target;
			this.IsExcluded = false;
		}

		public void Exclude()
		{
			this.IsExcluded = true;
		}
	}
}

