//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NeolithLib.API.Events
{
	public class PostHealEvent
	{
		public TakeDamage Target {get; set;}
		public IDBase Healer { get; set; }
		public float Amount { get; set; }
		public PreHealEvent.HealType Type { get; set; }
		public RepairEvent RepairEvent { get; set; }
		public bool WasCancelled { get; set; }
		public bool WasHandled { get; set; }
		public bool Handled { get; set; }

		public PostHealEvent (TakeDamage target, IDBase healer, float amount, PreHealEvent.HealType type, RepairEvent repairEvent, bool wasHandled, bool wasCancelled)
		{
			this.Target = target;
			this.Healer = healer;
			this.Amount = amount;
			this.Type = type;
			this.RepairEvent = repairEvent;
			this.WasCancelled = wasCancelled;
			this.WasHandled = wasHandled;
			this.Handled = false;
		}
	}
}

