//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NeolithLib.API.Events
{
	public class PostTakeDamageEvent
	{
		public TakeDamage Target { get; set; }
		public DamageEvent DamageEvent { get; set; }
		public bool WasCancelled { get; set; }
		public bool WasHandled { get; set; }
		public bool Handled { get; set; }

		public PostTakeDamageEvent (TakeDamage target, DamageEvent dmgEvent, bool wasHandled, bool wasCancelled)
		{
			this.Target = target;
			this.DamageEvent = dmgEvent;
			this.WasHandled = wasHandled;
			this.WasCancelled = wasCancelled;
		}
	}
}

