//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace NeolithLib
{
	public class PostGetPlayerCampEvent
	{
		public ServerManagement Management { get; set; }
		public PlayerClient PlayerClient { get; set; }
		public Vector3 Vector { get; set; }
		public Quaternion Quaternion { get; set; }
		public bool WasCancelled { get; set; }
		public bool WasHandled { get; set; }
		public bool Handled { get; set; }

		public PostGetPlayerCampEvent (ServerManagement management, PlayerClient playerClient, Vector3 vector, Quaternion quaternion, bool wasHandled, bool wasCancelled) 
		{
			this.Management = management;
			this.PlayerClient = playerClient;
			this.WasHandled = wasHandled;
			this.WasCancelled = wasCancelled;
			this.Handled = false;
			this.Vector = vector;
			this.Quaternion = quaternion;
		}
	}
}

