//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace NeolithLib.API.Events
{
	public class PreGetPlayerCampEvent
	{
		public ServerManagement Management { get; set; }
		public PlayerClient PlayerClient { get; set; }
		public bool Cancelled { get; set; }
		public Vector3 Vector { get; set; }
		public Quaternion Quaternion { get; set; }
		public bool Handled { get; set; }

		public PreGetPlayerCampEvent (ServerManagement management, PlayerClient playerClient)
		{
			this.Management = management;
			this.PlayerClient = playerClient;
			this.Cancelled = false;
			this.Handled = false;
		}
	}
}

