//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NeolithLib.API.Events
{
	public class PreHealEvent
	{
		public enum HealType
		{
			Regeneration,
			SingleShot,
			HealOverTime
		}

		public TakeDamage Target { get; set; }
		public IDBase Healer { get; set; }
		public float Amount { get; set; }
		public HealType Type { get; set; }
		public bool Cancelled { get; set; }
		public bool Handled { get; set; }

		public PreHealEvent (TakeDamage target, IDBase healer, float amount, HealType type)
		{
			this.Target = target;
			this.Healer = healer;
			this.Amount = amount;
			this.Type = type;
			this.Cancelled = false;
			this.Handled = false;
		}
	}
}

