//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NeolithLib.API.Events
{
	public class PreIsLockActiveEvent
	{
		public LockableObject LockableObject {get; set; }
		public bool Result { get; set; }
		public bool Handled { get; set; }
		public bool Cancelled { get; set; }

		public PreIsLockActiveEvent (LockableObject lockableObject)
		{
			this.LockableObject = lockableObject;
			this.Result = false;
			this.Handled = false;
			this.Cancelled = false;
		}
	}
}

