//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using NeolithLib.API.Events;
using NeolithLib.Bootstrapper;

namespace NeolithLib.API
{
	[Bootstrap]
	public class DeployableEvents : Facepunch.MonoBehaviour
	{
		private static DeployableEvents mInstance = null;
		
		public DeployableEvents() 
		{
			DeployableEvents.mInstance = this;
		}

		public void Awake()
		{
			DontDestroyOnLoad (this.gameObject);
		}

		public static void RegisterDeployableHandler<T>() where T : UnityEngine.MonoBehaviour
		{
			DeployableEvents.mInstance.gameObject.AddComponent<T> ();
		}

		public static bool InvokeOwnershipTest(DeployableObject target, Controllable user)
		{
			bool isOwner = target.BelongsTo (user);

			if (!isOwner) 
			{
				OwnershipInclusionEvent inclusionEvent = new OwnershipInclusionEvent(user, target);
				target.gameObject.SendMessage("OwnershipInclusionCommand", inclusionEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
				DeployableEvents.mInstance.gameObject.SendMessage("OwnershipInclusionCommand", inclusionEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
				isOwner = inclusionEvent.IsIncluded;
			}

			if (isOwner) 
			{
				OwnershipExclusionEvent exclusionEvent = new OwnershipExclusionEvent(user, target);
				target.gameObject.SendMessage("OwnershipExclusionCommand", exclusionEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
				DeployableEvents.mInstance.gameObject.SendMessage("OwnershipExclusionCommand", exclusionEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
				isOwner = !exclusionEvent.IsExcluded;
			}

			return isOwner;
		}

		public static void InvokeDeployableCreated(DeployableItemDataBlock dataBlock, ItemRepresentation itemRep, DeployableObject deployable, TransCarrier carrier, uLink.BitStream stream, ref uLink.NetworkMessageInfo info) {
			IInventoryItem item;
			itemRep.Item<IInventoryItem>(out item);
			Character character = item.inventory.inventoryHolder.GetComponent<Character>();

			PreCreateDeployableEvent preEvent = new PreCreateDeployableEvent(dataBlock, character, item, itemRep, deployable, carrier);
			itemRep.SendMessage("PreCreateDeployableCommand", preEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			character.SendMessage("PreCreateDeployableCommand", preEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			deployable.SendMessage("PreDeployableCreatingCommand", preEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			carrier.SendMessage("PreCreateCarriedDeployableCommand", preEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			DeployableEvents.mInstance.SendMessage("PreCreateDeployableCommand", preEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);

			if (!preEvent.Cancelled) {
				preEvent.DataBlock.SetupDeployableObject(stream, preEvent.ItemRepresentation, ref info, preEvent.DeployableObject, preEvent.Carrier);
			}

			PostCreateDeployableEvent postEvent = new PostCreateDeployableEvent (preEvent.DataBlock, preEvent.Character, preEvent.Item, preEvent.ItemRepresentation, preEvent.DeployableObject, preEvent.Carrier, preEvent.Handled, preEvent.Cancelled);
			itemRep.SendMessage ("PostCreateDeployableCommand", postEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			character.SendMessage ("PostCreateDeployableCommand", postEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			deployable.SendMessage ("PostDeployableCreatingCommand", postEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			carrier.SendMessage ("PostCreateCarriedDeployableCommand", postEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
			DeployableEvents.mInstance.SendMessage ("PostCreateDeployableCommand", postEvent, UnityEngine.SendMessageOptions.DontRequireReceiver);
		}
	}
}

